#
# Build stage
# Chứa các thành phần như: source code, dependencies (chỉ dùng cho bui)
FROM openjdk:8-jdk-alpine AS build
WORKDIR /build

COPY . .

RUN ./mvnw package -Dmaven.test.skip

#
# Package stage
#
FROM openjdk:8-jdk-alpine
WORKDIR /hello

COPY --from=build /build/target/*.jar hello.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","hello.jar"]