name: Publish package to the Maven Central Repository

on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
    - name: release
      run: npx semantic-release

# jobs:
#   build-n-publish:
#     name: Build and publish Java project
#     runs-on: ubuntu-latest
#     permissions: 
#       contents: read
#       packages: write 
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Set up Maven Central Repository
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'adopt'

#       - name: Publish package
#         run: mvn --batch-mode deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

