name: Publish package to the Maven Central Repository

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic   # Need an `id` for output variables
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update version pom.xml
      if: steps.semantic.outputs.new_release_published == 'true'
      run: mvn versions:set -DnewVersion=${{ steps.semantic.outputs.new_release_version }} -DprocessAllModules -DgenerateBackupPoms=false

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# jobs:
#   build-n-publish:
#     name: Build and publish Java project
#     runs-on: ubuntu-latest
#     permissions: 
#       contents: read
#       packages: write 
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Set up Maven Central Repository
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'adopt'

#       - name: Publish package
#         run: mvn --batch-mode deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

